### ISSUE TITLE
Websocket disconnect event not fired immediately

### ISSUE THREAD

**Issue by Rojoss** [heroiclabs/nakama-js#118]
When disconnecting the WIFI the Websocket disconnect event is not fired.
It seems like that it's only fired after like 30 seconds or when enabling the wifi again.
`socket.ondisconnect = this._onDisconnected.bind(this);`

As you can see in the gif here I added a breakpoint but it's never triggered.
Only when I turn the wifi back on it's triggered.
![ws_disconnect](https://user-images.githubusercontent.com/1093861/154727894-1d3ce2c2-c859-4420-9219-e2dbb8135019.gif)

**Comment by lugehorsam** [comment]
Hey @Rojoss this is currently expected behavior. You should expect timeouts on specific websocket calls (e.g., `sendMatchData`) but otherwise, whether the underlying socket detects a lack of connection is specific to the operating system.

An alternative would be to implement a ping/pong at your application layer, e.g., via `socket.rpc`. We'll explore adding the functionality at a later time.
